import json

# Store the data into a map
pose_info = {}

# Set number of classes
pose_info["classes_unmerged"] = 46
pose_info["classes_merged"] = 39

# Set merged class number for each pose
class_order = [
    0, 1, 2, 3, 4, 
    3, 5, 6, 7, 6, 
    8, 9, 10, 9, 10, 
    11, 12, 13, 14, 15, 
    16, 17, 18, 19, 20, 
    21, 22, 22, 22, 21, 
    23, 24, 25, 26, 27, 
    28, 29, 30, 31, 32, 
    33, 34, 35, 36, 37, 38]
class_map = {}
for i in range(len(class_order)):
    class_map[i] = class_order[i]

pose_info["class_map"] = class_map

# Set long and short names for each pose
pose_info["names"] = {}
pose_info["names"]["long_unmerged"] = [
    "Transitional Poses",
    "Preparation",
    "Opening",
    "Part the Wild Horse's Mane, 1st Left",
    "Part the Wild Horse's Mane, Right",
    "Part the Wild Horse's Mane, 2nd Left",
    "White Crane Spreads Its Wings",
    "Brush knee and Step Forward, 1st Right",
    "Brush knee and Step Forward, Left",
    "Brush knee and Step Forward, 2nd Right",
    "Play Lute (pipa)",
    "Step Back, Reeling Forearms (repulse Monkey), 1st Right",
    "Step Back, Reeling Forearms (repulse Monkey), 1st Left",
    "Step Back, Reeling Forearms (repulse Monkey), 2nd Right",
    "Step Back, Reeling Forearms (repulse Monkey), 2nd Left",
    "Grasp Sparrow's Tail on Left, Hold the Ball",
    "Grasp Sparrow's Tail on Left, Ward off (peng)",
    "Grasp Sparrow's Tail on Left, Stroke (lv)",
    "Grasp Sparrow's Tail on Left, Squeeze",
    "Grasp Sparrow's Tail on Left, Push",
    "Grasp Sparrow's Tail on Right, Hold the Ball",
    "Grasp Sparrow's Tail on Right, Ward off (peng)",
    "Grasp Sparrow's Tail on Right, Stroke (lv)",
    "Grasp Sparrow's Tail on Right, Squeeze",
    "Grasp Sparrow's Tail on Right, Push",
    "Single Whip",
    "Cloud Hands, 1st",
    "Cloud Hands, 2nd",
    "Cloud Hands, 3rd",
    "Single Whip",
    "Stroke Horse's Back",
    "Cross Hands, Right Heel Kick",
    "Double Bees Bussing at Ears (strike opponent's ears with two fists)",
    "Turn, Cross Hands, and Left Heel Kick",
    "Snake Creeps Down Left Leg",
    "Golden Rooster Stands on Left Leg (single whip low and stand on left leg)",
    "Snake Creeps Down Right Leg",
    "Golden Rooster Stands on Right Leg (single whip low and stand on left leg)",
    "Jade Lady Works Shuttles, Left",
    "Jade Lady Works Shuttles, Right",
    "Needle at Sea Bottom",
    "Ward Off and Push Away",
    "Turn, Intercept, and Punch",
    "As If Closing Shut",
    "Cross",
    "Closing"
]

pose_info["names"]["long_merged"] = [
    "Transitional Poses",
    "Preparation",
    "Opening",
    "Part the Wild Horse's Mane, Left",
    "Part the Wild Horse's Mane, Right",
    "White Crane Spreads Its Wings",
    "Brush knee and Step Forward, Right",
    "Brush knee and Step Forward, Left",
    "Play Lute (pipa)",
    "Step Back, Reeling Forearms (repulse Monkey), Right",
    "Step Back, Reeling Forearms (repulse Monkey), Left",
    "Grasp Sparrow's Tail on Left, Hold the Ball",
    "Grasp Sparrow's Tail on Left, Ward off (peng)",
    "Grasp Sparrow's Tail on Left, Stroke (lv)",
    "Grasp Sparrow's Tail on Left, Squeeze",
    "Grasp Sparrow's Tail on Left, Push",
    "Grasp Sparrow's Tail on Right, Hold the Ball",
    "Grasp Sparrow's Tail on Right, Ward off (peng)",
    "Grasp Sparrow's Tail on Right, Stroke (lv)",
    "Grasp Sparrow's Tail on Right, Squeeze",
    "Grasp Sparrow's Tail on Right, Push",
    "Single Whip",
    "Cloud Hands",
    "Stroke Horse's Back",
    "Cross Hands, Right Heel Kick",
    "Double Bees Bussing at Ears (strike opponent's ears with two fists)",
    "Turn, Cross Hands, and Left Heel Kick",
    "Snake Creeps Down Left Leg",
    "Golden Rooster Stands on Left Leg (single whip low and stand on left leg)",
    "Snake Creeps Down Right Leg",
    "Golden Rooster Stands on Right Leg (single whip low and stand on right leg)",
    "Jade Lady Works Shuttles, Left",
    "Jade Lady Works Shuttles, Right",
    "Needle at Sea Bottom",
    "Ward off and Push Away",
    "Turn, Intercept, and Punch",
    "As If Closing Shut",
    "Cross",
    "Closing"
]

pose_info["names"]["short_unmerged"] = [
    "Transitions",
    "Prep",
    "Open",
    "PWHM, 1st Left",
    "PWHM, Right",
    "PWHM, 2nd Left",
    "WCSW",
    "BKSF, 1st Right",
    "BKSF, Left",
    "BKSF, 2nd Right",
    "Play Lute",
    "SBRF, 1st Right",
    "SBRF, 1st Left",
    "SBRF, 2nd Right",
    "SBRF, 2nd Left",
    "GTSL, Hold the Ball",
    "GTSL, Ward off",
    "GTSL, Stroke",
    "GTSL, Squeeze",
    "GTSL, Push",
    "GTSR, Hold the Ball",
    "GTSR, Ward off",
    "GTSR, Stroke",
    "GTSR, Squeeze",
    "GTSR, Push",
    "Single Whip",
    "Cloud Hands, 1st",
    "Cloud Hands, 2nd",
    "Cloud Hands, 3rd",
    "Single Whip",
    "Stroke Horse's Back",
    "CH, Right HK",
    "DBBE",
    "Turn, CH, and Left HK",
    "SCD Left",
    "GRS Left",
    "SCD Right",
    "GRS Right",
    "JLWS, Left",
    "JLWS, Right",
    "Needle at Sea Bottom",
    "WOPA",
    "TIP",
    "As If Closing",
    "Cross",
    "Close"
]

pose_info["names"]["short_merged"] = [
    "Transitions",
    "Prep",
    "Open",
    "PWHM, Left",
    "PWHM, Right",
    "WCSW",
    "BKSF, Right",
    "BKSF, Left",
    "Play Lute (pipa)",
    "SBRF, Right",
    "SBRF, Left",
    "GSTL, Hold the Ball",
    "GSTL, Ward off",
    "GSTL, Stroke",
    "GSTL, Squeeze",
    "GSTL, Push",
    "GSTR, Hold the Ball",
    "GSTR, Ward off (peng)",
    "GSTR, Stroke (lv)",
    "GSTR, Squeeze",
    "GSTR, Push",
    "Single Whip",
    "Cloud Hands",
    "Stroke Horse's Back",
    "CH, Right HK",
    "DBBE",
    "Turn, CH, and Left HK",
    "SCD Left",
    "GRS Left",
    "SCD Right",
    "GRS Right",
    "JLWS, Left",
    "JLWS, Right",
    "Needle at Sea Bottom",
    "WOPA",
    "TIP",
    "As If Closing",
    "Cross",
    "Close"
]

# Output the file
with open('pose_info.json', 'w+') as file_out:
    json.dump(pose_info, file_out, sort_keys=True, indent=4)